export {
  ArrowDownIcon,
  ArrowUpIcon,
  BrowserIcon,
  BriefcaseIcon,
  CaretDownIcon,
  CertificateIcon,
  CodeIcon,
  CursorClickIcon,
  DeviceMobileIcon,
  DownloadSimpleIcon,
  EnvelopeIcon,
  FileTextIcon,
  GithubLogoIcon,
  GlobeHemisphereWestIcon,
  GlobeIcon,
  GraduationCapIcon,
  HouseIcon,
  LinkedinLogoIcon,
  ListIcon,
  ShoppingCartSimpleIcon,
  SlidersHorizontalIcon,
  StackIcon,
  UserIcon,
  XIcon,
} from '@phosphor-icons/react';
